#!/usr/bin/perl
# (c) goose121, 2017-2026
# Released under the MIT license
# Contributions for OpenRC Daemon/Placeholder support added 2026

use warnings;
use strict;
use v5.10.1;
use Getopt::Long;
use Pod::Usage;

my $type = "simple";
my @cmds_start = ();
my @cmds_stop = ();
my $pidfile = "";
my $desc = "";
my $user = "";
my $group = "";

# parse CLI args
my %opt;
GetOptions(\%opt,
           "name=s",
           "help|?") || pod2usage(2);
pod2usage() if ($opt{help});

# sanity checks
my $USAGE = "Usage: initify [options] some-systemd.service";
unless (@ARGV > 0 && $ARGV[0] =~ /(.*\/)?([^\/.]*)\.service/) {
    print "no *.service file specified - quitting\n$USAGE\n";
    exit;
}
unless (-e "$ARGV[0]") {
    print "can not find *.service file: '$ARGV[0]' - quitting\n$USAGE\n";
    exit;
}

# get systemd service source file, and target service name
(my $service = $ARGV[0]) =~ s/\.service//;
(my $svc_name = $ARGV[0]) =~ s|(.*/)?([^/.]*)\.service|$2|;
$svc_name = $opt{name} if (length $opt{name});

# parse systemd unit
while(<>) {
    chomp;
    s/^\s+|\s+$//g; # Trim whitespace
    
    if (m/^Type\s*=\s*(.*)/i) { $type = lc($1); }
    if (m/^Description\s*=\s*(.*)/i) { $desc = $1; }
    if (m/^PIDFile\s*=\s*(.*)/i) { $pidfile = $1; }
    if (m/^User\s*=\s*(.*)/i) { $user = $1; }
    if (m/^Group\s*=\s*(.*)/i) { $group = $1; }
    
    if (m/^ExecStart\s*=\s*(.*)/i) {
        if (length $1) { push(@cmds_start, $1); }
        else { @cmds_start = (); }
    }
    if (m/^ExecStop\s*=\s*(.*)/i) {
        if (length $1) { push(@cmds_stop, $1); }
        else { @cmds_stop = (); }
    }
}

# Prepare command parts
my @cmd_path;
my @cmd_argl;

foreach my $cmd (@cmds_start) {
    my @sep = split(/ /, $cmd, 2);
    push(@cmd_path, $sep[0]);
    push(@cmd_argl, $sep[1] // "");
}

# --- OpenRC Logic Patches ---

# 1. Handle Systemd placeholders (%i, %I) for OpenRC sub-services
# Maps %i to ${RC_SVCNAME#*.} so /etc/init.d/svc.instance works
foreach (@cmd_argl) { s/%[iI]/\${RC_SVCNAME#*.}/g; }
$pidfile =~ s/%[iI]/\${RC_SVCNAME#*.}/g;

# 2. Determine Daemon/Backgrounding requirements
my $ssd_opts = "";
if ($type eq "simple") {
    # Simple types stay in foreground; OpenRC must daemonize them
    $ssd_opts = "--background --make-pidfile";
    $pidfile = "/run/\${RC_SVCNAME}.pid" unless $pidfile;
}

# --- Generate OpenRC Script ---

open(my $fh, '>', "$service") || die("Cannot create $service: $!\n");

print $fh <<"EOF";
#!/sbin/openrc-run
# Generated by initify - https://github.com/goose121/initify

name="\$RC_SVCNAME"
description="$desc"

command="$cmd_path[0]"
command_args="$cmd_argl[0] $ssd_opts"
pidfile="$pidfile"
EOF

# Add User/Group if defined
print $fh "command_user=\"$user:$group\"\n" if ($user);

print $fh <<'EOF';

depend() {
	after net
	use dns logger
}

start_pre() {
	# Ensure runtime directory for PID exists
	checkpath -d -m 0755 -o ${command_user:-root} /run/${RC_SVCNAME%/*}
}
EOF

close $fh;
print "Successfully converted to OpenRC: $service\n";

__END__

=head1 NAME

initify - Convert systemd units to OpenRC init-files (Patched for 2026)

=head1 SYNOPSIS

    initify [options] file.service

=head2 Summary of Improvements

=over 4

=item * Backgrounding

Automatically adds --background and --make-pidfile for Type=simple units.

=item * Placeholder Support

Translates %i/%I to OpenRC-compatible shell variables for multi-instance scripts.

=item * User/Group

Correctly maps Systemd User/Group to command_user.

=back

=cut
